export enum PageTitles {
    REGISTRATION = 'Registration',
    LOGIN = 'Login',
    ACTIVATION_PAGE = 'Activation page',
    MANAGING = 'Managing',
    ERROR = 'Error',
    ADD_LIBRARIAN = 'Librarian adding',
    ADD_STUDENT = 'Student adding',
    LIBRARIAN_DETAILS = 'Librarian',
    STUDENT_DETAILS = 'Student',
    LIBRARIANS = 'Librarians',
    STUDENTS = 'Students',
    STATISTIC = 'Statistic',
    LOANS = 'Loans',
    ADD_BOOK = 'Book adding',
    BOOK_DETAILS = 'Book',
    CATALOG = 'Catalog',
    ORDERS = 'Orders',
    PROFILE = 'Profile'
}
